spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5

#配置mybatis
mybatis:
  #核心配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  #mapper映射位置
  mapper-locations: classpath:mybatis/mapper/*.xml


