spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置jpa
  jpa:
    hibernate:
      #更新或者创建数据库
      ddl-auto: update
      #控制台显示SQL语句
    show-sql: true